# Generated by Django 2.2.4 on 2019-09-11 08:32

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticles',
            name='avatar_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(default=0, upload_to='avatars'),
            preserve_default=False,
        ),
    ]
