# Generated by Django 2.2.4 on 2019-09-14 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogarticles_avatar_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticles',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
