# Generated by Django 2.2.4 on 2019-09-28 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdfs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='name',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pdf',
            name='title',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='article.ArticlePost'),
        ),
    ]
