# Generated by Django 2.2.4 on 2019-09-11 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='message_subject',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
