# Generated by Django 2.2.4 on 2019-09-23 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_auto_20190923_1922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('-created',)},
        ),
        migrations.RemoveField(
            model_name='image',
            name='publish',
        ),
    ]
