# Generated by Django 2.2.4 on 2019-09-15 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190915_1719'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='newspost',
            index_together={('id', 'slug')},
        ),
    ]
