# Generated by Django 2.2.4 on 2019-09-15 12:05

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20190915_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='avatar_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(upload_to='avatars'),
        ),
    ]
