# Generated by Django 2.2.4 on 2019-09-23 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20190916_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='article_writer',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
